[WIP] - Agregando donadores
JSConfCL/gql_api pull request #97
Opened 2023-11-21 08:40 UTC by fforres

2023-11-27 12:16 UTC, Benjvvp approved these changes
Para mas adelante seria bueno testear lo de mercado pago o no? jajaj apero nice wp 💯

2023-11-27 15:34 UTC, rodrigobustamante requested changes

2023-11-27 15:34 UTC, rodrigobustamante commented on src/generated/types.ts
> +export enum SearchableUserTags {
Este enum podría quedar común, tipo shared maybe
Veo que se define [acá](https://github.com/JSConfCL/gql_api/pull/97/files#diff-405a041ca0e58015fdeddd9997ae1082b8e7c7ea27326a8b3f09ce47efc35997R7) también

2023-11-27 15:34 UTC, rodrigobustamante commented on src/index.ts
> +          return maskError(error, message, APP_ENV !== "production");
Variables como production, podrían quedar quizá en una variable, para no tener string sueltos quizá

2023-11-27 15:34 UTC, rodrigobustamante commented on src/schema/user.ts
> +      if (tags && tags.length !== 0) {
Optional chaining quizá?
`!!tags?.length`

2023-11-27 15:34 UTC, rodrigobustamante commented on src/tests/user/searchUser.generated.ts
> +    `;
Faltó un line break al final del archivo

2023-11-27 15:34 UTC, rodrigobustamante commented on src/tests/__fixtures/index.ts
Se podrá quizá dejar los tests en algún folder tipo __tests__?
Y los fixtures en __fixtures__?

O dejo realmente, de porqué no se tiene el test al nivel del archivo testeado tipo:

├── src/
│   └── utils/
│       ├── dateFormat.ts
│       └── dateFormat.test.ts

2023-11-27 15:34 UTC, rodrigobustamante commented on workers/wall_of_fame_cron/api.mercadopago.ts
> +  const DB = getDb({
En caso de que no se pueda conectar a la db, no sería necesario un try catch?

2023-11-28 01:56 UTC, fforres commented on src/generated/types.ts
> +export enum SearchableUserTags {
Aaah, lo que está bajo `src/generated/**` está generado automáticamente en base al esquema de `Graphql` que la API expone... esto es para que nuestros tests de integración se parezcan lo que mas se pueda a como se usarían en el frontend.

2023-11-28 01:59 UTC, fforres commented on src/index.ts
> +          return maskError(error, message, APP_ENV !== "production");
Sii :) `APP_ENV` es type-enforced, entonces al menos estos strings sueltos están forzados a ser de un tipo específico.

Deberíamos tener algun archivo de variables, agree 🙏  Voy a crear un issue :)

2023-11-28 02:04 UTC, fforres commented on src/tests/user/searchUser.generated.ts
> +    `;
Estos archivos `*.generated.ts` son creados automáticamente por el `npm run generate`, yo no me preocuparía mucho por ellos la verdad.

Ahora, para forzar patrones, personalmente me importa poco que patrones queramos seguir.... mientras se automatize el chequeo. onda.... es una lata PR por medio tener que mandar/recibir "Deberíamos agregar un `;` acá" 😆 así que mientras podamos meter esos checks en un linter o algo parecido, por mi 0 drama 👍

2023-11-28 02:07 UTC, fforres commented on src/tests/__fixtures/index.ts
> Se podrá quizá dejar los tests en algún folder tipo tests?
Estoy un poco confundido... con hoy por hoy están bajo una carpeta `tests`  🤔 (`src/test`)

Cambiar todos los tests de lugar es un refactor masmenos grande.... si bien no tengo opiniones fuertes, (mientras tengamos tests digo 🤔 ) cual sería la ventaja/ganancia con cambiar de estructura?

2023-11-28 02:10 UTC, rodrigobustamante commented on src/generated/types.ts
> +export enum SearchableUserTags {
Omitir entonces completamente mi comentario jajaja

2023-11-28 02:11 UTC, fforres commented on workers/wall_of_fame_cron/api.mercadopago.ts
> +  const DB = getDb({
Existe! Pero a diferente nivel...la verdad acá en esta linea, no está creando una conexión a la BDD, solo creando el conector con la URL/Token específica, la conexión a la BDD ocurre cuando hacemos un ... `await DB.query` dentro de los resolvers por ejemplo.

Y esos están capturados (y enmascarados para q no hagamos un leak de las partes internas de la app) por esta función https://github.com/JSConfCL/gql_api/blob/fforres/donadores/src/index.ts#L125-L131

2023-11-28 02:11 UTC, rodrigobustamante commented on src/tests/user/searchUser.generated.ts
> +    `;
Podemos armar un issue para crear o modificar el linter actual? Me llevo la implementación (ando del cel revisando PRs, es esto el primer mundo(?))

2023-11-28 02:12 UTC, rodrigobustamante commented on src/tests/__fixtures/index.ts
Principalmente tener facilidad a los ojos el saber si el archivo tiene test o no (opinión personal)

2023-11-28 02:22 UTC, fforres commented on workers/wall_of_fame_cron/api.mercadopago.ts
> +  const DB = getDb({
Mas que nada para dejar emeplos y no usar barrel files.

En backend no es tan terrible, pero tener un archivo index que realize re-exports.por ejemplo, es un infierno en el frontend (y receta fija pa hacer pebre la perfomance de tu app).

En la version corta, es para facilitar patrones parecidos entre frontend y backend

2023-11-28 02:24 UTC, fforres commented on src/tests/__fixtures/index.ts
Me parece :)
Si ayuda en el general, demosle.
Va a ser decente ese PR si 😬😬😬

2023-11-28 02:25 UTC, rodrigobustamante commented on workers/wall_of_fame_cron/api.mercadopago.ts
> +  const DB = getDb({
Depende el fin de la app encuentro, si es una lib, estoy completamente de acuerdo, pero si es una app que llama sus propios componentes, no es taaaan terrible

2023-11-28 02:26 UTC, rodrigobustamante commented on src/tests/__fixtures/index.ts
Abramos debate! Si damos el go, me lo llevo!

2023-11-28 02:26 UTC, fforres commented on src/tests/user/searchUser.generated.ts
> +    `;
Es harto... Pero es re util tener tipos autogenerados. (Frontend y backend)

Creo que mas que modificar el.linter seria tener discusiones de reglas específicas, con las que tengamos algun tema....

O quieres modificar el linter completo?

2023-11-28 03:03 UTC, rodrigobustamante commented on src/tests/user/searchUser.generated.ts
> +    `;
Ya, te entendí, omite y debatimos después con el equipo!

2023-11-28 03:20 UTC, fforres commented on workers/wall_of_fame_cron/api.mercadopago.ts
> +  const DB = getDb({
Yo diria al reves. Claro que En un app grande si (varios equipos, erc) el impacto negativo de un par de barrel.filea es mucho mayor, so retodo si no tienes como enforzar una estructura de carpetas/imports.


Onda... Dominio A pesa 1 mega, importa una pura cosa de Dominio B, pero la importa desde el barrel file... Ahora todo el dominio B esta importado dentro del dominio A. 
Con librerías es menos el impacto porque usualmente no estas intentando hacer code splitting dinamico ponte tu...

La verdad es un rant que da pa super largo xD 
Pero la cosa es que los barrel causan caleta de issues a los bundlers :(

2023-11-28 17:46 UTC, rodrigobustamante commented on workers/wall_of_fame_cron/api.mercadopago.ts
> +  const DB = getDb({
Igual si me puedes dar una KT sobre eso, yo feliz <3

2023-11-29 16:19 UTC, fforres commented on workers/wall_of_fame_cron/api.mercadopago.ts
> +  const DB = getDb({
He andado corriendo mil. Voy a mergear y creo los tickets en la tarde

2023-11-29 16:19 UTC, merged